// checklists.js
export const initialChecklist = [
    { task: "Make safe as instructed in the service manual", done: false, remark: "", inputs: {} },
    { task: "Carry out repair (after obtaining authorization, if needed)", done: false, remark: "", inputs: {} },
    { task: "Check abnormality in Ambient air like Bad odor / Heavy dust", done: false, remark: "", inputs: {} },
    { task: "Check control cabinet / cooler filter mats, clean / replace if necessary", done: false, remark: "", inputs: {} },
    { task: "Check / clean cooler, check fan blades and guarding", done: false, remark: "", inputs: {} },
    { task: "Check coupling / belt tension, tight if necessary", done: false, remark: "", inputs: {} },
    { task: "Check / change oil separator cartridge", done: false, remark: "", inputs: {} },
    { task: "Check oil separator cartridge, diff. pressure", done: false, remark: "", inputs: {} },
    { task: "Check / change the Air filter", done: false, remark: "", inputs: {} },
    { task: "Check Air filter cap, Suction hose for any leak or crack / damage", done: false, remark: "", inputs: {} },
    { task: "Check / change the Oil filter", done: false, remark: "", inputs: {} },
    { task: "Check / change the Oil", done: false, remark: "", inputs: {} },
    { task: "Check / change the Valve kits", done: false, remark: "", inputs: {} },
    { task: "Check motor bearing lubrication, regrease if necessary", done: false, remark: "", inputs: {} },
    { task: "Check electrical connection and tight if necessary", done: false, remark: "", inputs: {} },
    { task: "Check motor overcurrent relays and protection switches", done: false, remark: "", inputs: {} },
    { task: "Check door and guard interlocks and emergency stop function", done: false, remark: "", inputs: {} },
    { task: "Check all sensor connections and tight if necessary", done: false, remark: "", inputs: {} },
    { task: "Check and register if any safety device bypassed", done: false, remark: "", inputs: {} },
    { task: "Check Control voltage; L1 <TextField> V, Logo Power Output <TextField> V DC.", done: false, remark: "", inputs: {} },
    { task: "Check line voltage: L1 <TextField> V, L2 <TextField> V, L3 <TextField> V <TextField>", done: false, remark: "", inputs: {} },
    { task: "Check current consumption: Line U1 <TextField> A, V1 <TextField> A, W1 <TextField> A ……..", done: false, remark: "", inputs: {} },
    { task: "Check Fan motor current Fan 1 U1 <TextField> A, V1 <TextField> A, W1 <TextField> A", done: false, remark: "", inputs: {} },
    { task: "Check Fan motor current Fan 2 U1 <TextField> A, V1 <TextField> A, W1 <TextField> A", done: false, remark: "", inputs: {} },
    { task: "Room temp: <TextField> C, Airend discharge temp.: <TextField> C <TextField>", done: false, remark: "", inputs: {} },
    { task: "Pressure Setting: SP <TextField> bar, SD <TextField> bar", done: false, remark: "", inputs: {} },
    { task: "Check for any Air / Oil leakages in the compressor<TextField>", done: false, remark: "", inputs: {} },
    { task: "Check and maintain ZK filter Eco drain Valve <TextField>", done: false, remark: "", inputs: {} },
    { task: "Test run, check conditions: start, idle, load and shut-down <TextField>", done: false, remark: "", inputs: {} },
  ];
  
  export const initialRefrigeratorList = [
    { task: "Check refrigerant levels", done: false, remark: "", inputs: {} },
    { task: "Inspect evaporator and condenser coils", done: false, remark: "", inputs: {} },
    { task: "Check door seals for damage", done: false, remark: "", inputs: {} },
    { task: "Clean drain pan and ensure proper drainage", done: false, remark: "", inputs: {} },
    { task: "Verify thermostat operation", done: false, remark: "", inputs: {} },
    { task: "Check / clean Air dryer condenser", done: false, remark: "", inputs: {} },
    { task: "Check condenser fan motor direction", done: false, remark: "", inputs: {} },
    { task: "Check condensate drain function", done: false, remark: "", inputs: {} },
    { task: "Check refrigerant circuit and Air circuit for leaks", done: false, remark: "", inputs: {} },
    { task: "Check compressed air temperature: Inlet <TextField> °C | Outlet <TextField> °C", done: false, remark: "", inputs: {} },
    { task: "Check current consumption: Line U1 <TextField> A, V1 <TextField> A, W1 <TextField> A", done: false, remark: "", inputs: {} },
    { task: "Check Auto On/Off operation; Switching On <TextField> C, Switching Off <TextField> C", done: false, remark: "", inputs: {} },
    { task: "Pressure dew point [ ] blue [ ] green [ ] red <TextField> °F/C", done: false, remark: "", inputs: {} },
    { task: "Check / Replace Air treatment filter cartridge", done: false, remark: "", inputs: {} },
  ];
  